# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: ssh-keygen
        run: |
          ssh-keygen -t rsa -b 4096 -C "id_rsa" -f /home/runner/.ssh/id_rsa -N ""
          ssh-keygen -t rsa -b 4096 -C "ansible" -f /home/runner/.ssh/ansible -N ""

      - name: Copy public key to bastion host
        run: |
          ssh-copy-id -i /home/runner/.ssh/id_rsa rmira@bastion-1.acad.opswerks.net

      - name: ssh into machine
        run: ssh rmira@bastion-1.acad.opswerks.net

      - name: print working directory
        run: pwd
